version: '3.4'

services:
        app:
                tty: true
                stdin_open: true
                build:
                        context: .
                        dockerfile: Dockerfile
                command: bash -c "bundle install && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'" 
                depends_on:
                        - database
                        - redis
                ports:
                        - "3000:3000"
                        - "4000:4000"
                volumes:
                        - .:/app
                        - gem_cache:/usr/local/bundel/gems/
                        - node_modules:/app/node_modules/
                env_file: .env
                environment:
                        RAILS_ENV: development
                        HUB_URL: http://chrome:4444/wd/hub

        database:
                image: postgres:12.1
                volumes:
                        - db_data:/var/lib/postgresql/data
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

        chrome:
                image: selenium/standalone-chrome
                ports:
                        - "5900:5900"
        
        redis:
                image: redis:5.0.7

        sidekiq:
                build:
                        context: .
                        dockerfile: Dockerfile
                depends_on:
                        - app
                        - database
                        - redis
                volumes:
                        - .:/app
                        - gem_cache:/usr/local/bundle/gems
                        - node_modules:/app/node_modules
                env_file: .env
                environment:
                        RAILS_ENV: development
                entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
        gem_cache:
        db_data:
        node_modules:
